apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 2100
      cpuLimitMili: 2100
      memoryRequestMb: 350
      memoryLimitMb: 1411
      args: []
      command:
        - hellow
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: test-app-34-main
      imagePullPolicy: Always
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: test-app-34
    version: v0.0.1
    applicationId: app_c27eba9c-e8e3-4c21-bb84-0699bbd085b3
    projectId: project_ed1339d0-eb8f-4689-928f-cbc356826314
    organizationId: org_c2a5c30e-de81-4d82-84d0-8627af8bcc64
    environmentId: env_b2e9fc14-d62d-4ae7-ad89-fd9cfe4a5b0d
    environmentName: staging
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: test-app-34
  cronTab: ''
  serviceType: ClusterIP
  namespace: project-console-01-staging
