apiVersion: v1
kind: Namespace
metadata:
  name: project-console-01-staging
  labels:
    environment-id: env_b2e9fc14-d62d-4ae7-ad89-fd9cfe4a5b0d
    project-id: project_ed1339d0-eb8f-4689-928f-cbc356826314
    project-name: project-console-01
    environment-name: staging
    organization-id: org_c2a5c30e-de81-4d82-84d0-8627af8bcc64
