apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-local-01
  labels:
    app: app-local-01
    applicationId: app_241f8c64-7576-43f0-a016-06f5e1cb1ba2
    version: v0.0.1
spec:
  selector:
    matchLabels:
      app: app-local-01
  template:
    metadata:
      labels:
        app: app-local-01
