apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: app-local-01
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-local-01
