apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts:
        - port: 123321
          targetPort: 12332
          protocol: UDP
        - port: 123123
          targetPort: 123123
          protocol: UDP
      healthChecks: []
      name: console-test-app-main
      imagePullPolicy: Always
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: console-test-app
    version: v0.0.1
    applicationId: app_6dc3cbe2-c662-46b5-b847-9f62e3bbf23f
    projectId: project_ed1339d0-eb8f-4689-928f-cbc356826314
    organizationId: org_c2a5c30e-de81-4d82-84d0-8627af8bcc64
    environmentId: env_799712fe-7685-4d4a-be07-1a99e86966f1
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: console-test-app
  cronTab: ''
  serviceType: ClusterIP
  namespace: project-console-01-dev
