apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: local-app-3
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: local-app-3
